### ISSUE TITLE
Mismatched Armor Sets 

### ISSUE THREAD

**Issue by Blank5SZ** [Guitarninja2/thepath#10]
both the sky breaker set and the Selena's legacy set are bugged out with missing puldrons and armor pieces levitating off the body  I'm not sure what the issue is but i know its not race Related Because i tried switching races as well and that did not fix the armor bugs i was having Just give it a look Thank you
![20220504014920_1](https://user-images.githubusercontent.com/104533116/166624819-66c9e9cc-f8e5-4638-9f74-c5b585d4270e.jpg)
![20220504014918_1](https://user-images.githubusercontent.com/104533116/166624827-c94dd7d7-0c98-4465-a14c-050ead036bd8.jpg)
![20220504014915_1](https://user-images.githubusercontent.com/104533116/166624834-cab3f208-ec2a-4761-801f-ceec5a933456.jpg)
![20220504014905_1](https://user-images.githubusercontent.com/104533116/166624837-ad1a2d12-c211-4825-8999-85d15fad75b2.jpg)
![20220504014903_1](https://user-images.githubusercontent.com/104533116/166624841-c4afe27c-4886-47d6-9b19-e61eb41f6d69.jpg)
![20220504014900_1](https://user-images.githubusercontent.com/104533116/166624845-12cfd272-caa7-4d53-8e9f-c947c44e7f20.jpg)

**Comment by Guitarninja2** [comment]
I believe those edits are intentionally done by https://www.nexusmods.com/enderalspecialedition/mods/208
