### ISSUE TITLE
All the Furniture In My House Such as tables and shelves and such are missing!

### ISSUE THREAD

**Issue by Blank5SZ** [Guitarninja2/thepath#11]
I bought myself a House in the Ark Market And Headed there and it seems that all my tables and furniture is gone There are some chairs there and the bed is still there but I'm missing My Crafting And Enchanting tables my shelves and tables are gone so all the static Objects are Floating Have not Altered or changed anything in the load order
![20220504040157_1](https://user-images.githubuser
![20220504040200_1](https://user-images.githubusercontent.com/104533116/166636249-583713d0-682f-4463-a45d-59732b4de226.jpg)
![20220504040204_1](https://user-images.githubusercontent.com/104533116/166636255-21038786-b3d7-497d-a3ad-9bb105327caf.jpg)
![20220504040208_1](https://user-images.githubusercontent.com/104533116/166636261-208a1ef0-4b5c-4ebc-b8d2-8e831abfa9bd.jpg)

content.com/104533116/166636244-60024444-1a1a-46fa-b8a0-ad3159a69e5c.jpg)

**Comment by Guitarninja2** [comment]
Should be fixed in 1.1
