### ISSUE TITLE
"Daddy" won't feast on the deer (animation won't play)

### ISSUE THREAD

**Issue by ArceyTheSecond** [Guitarninja2/thepath#15]
Fresh installation, version 1.0.1.

Near the end of the first dream Daddy is supposed to crouch down and feast upon the deer. However, this animation doesn't play.
Normally this has to do with the custom skeleton (using FNIS) used by the Enderal dev's and those animations not being added/updated by added mods. Most likely this causes issues with other animations too.

**Comment by ArceyTheSecond** [comment]
Alright, I (cautiously) believe I've found the solution.

In short:

- Install "[Enderal- Fores New Idles Patch - FNIS Patch](https://www.nexusmods.com/skyrim/mods/76979)", and put the loadorder right above "Nemesis".
- Manually add the "Start in" for Nemesis Unlimited Behavior Engine in MO2 as it was empty (not sure if this step was necessary)
- Manually disable Real-Time protection from Windows Defender as mentioned [here](https://www.reddit.com/r/skyrimmods/comments/pgvwz9/psa_for_those_of_you_getting_nemesis_unlimited/) to get it running.
- Run Nemesis Unlimited Behavior Engine and Update / Run

Afterwards my animations for (at least) daddy's munching were restored. Yay!

**Comment by Guitarninja2** [comment]
Hey thank you for checking this out. I'll see if I can get an update out relatively soon with this fix.

**Comment by ArceyTheSecond** [comment]
Sweet. Here is to hoping this will also work with the pipe smoking and Calia specific animations though, will have to verify this later on.

**Comment by Guitarninja2** [comment]
Yeah that would be ideal. I will need to find a save file to test it on soon.

**Comment by ArceyTheSecond** [comment]
![image](https://user-images.githubusercontent.com/105483909/168375906-3331db30-a1d6-40ed-b256-6e89e62a575c.png)

Here's how I set the Nemesis engine, just to be 100% complete.

**Comment by Guitarninja2** [comment]
Yeah this seems to do it. I need to test the calia animation real quick

**Comment by ArceyTheSecond** [comment]
> Hmm. The intro scene seemed to play fine for me.

That's weird... I'll do some more digging then. I take it things like outputfiles you generated with Nemesis were included in 1.1.0? (Or does Wabbajack do that? I don't know.)

**Comment by Guitarninja2** [comment]
Yeah my output files are just included directly in the bundle.

**Comment by ArceyTheSecond** [comment]
Pffft. I just can't seem to get it to work. It's so infuriating. I'll report back if I find anything.
