### ISSUE TITLE
Conversation text disappears during "Secrets from the Can" 

### ISSUE THREAD

**Issue by MisterB1969** [Guitarninja2/thepath#4]
I've had this issue before on my own personal mod-list; But during the "Secrets from the Can" . The conversation text with silas disappears after you show him the "Poem" or "Riddle". I tracked my problem to the UI overhaul I was using in my own list.

**Comment by Guitarninja2** [comment]
Yeah I think it's related to convenient dialogue UI. It'll likely need to be removed.

**Comment by Guitarninja2** [comment]
Fixed for the 1.0 release
