### ISSUE TITLE
Potential additions to the list

### ISSUE THREAD

**Issue by Sylien** [Guitarninja2/thepath#5]
Not Enderal Specific:
[Expressive Facial Animation -Female Edition-](https://www.nexusmods.com/skyrimspecialedition/mods/19181) - Expressive faces adds a lot for me.
[Expressive Facial Animation -Male Edition-](https://www.nexusmods.com/skyrimspecialedition/mods/19532) - The base game expressions are just so flat.
[VHR - Vanilla Hair Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/25574) - I just like this hair replacer a lot, it's very unintrusive.
[Better Stealing](https://www.nexusmods.com/skyrimspecialedition/mods/32295) - I like to be able to pick stuff up in an empty house without this stuff being flagged as stolen.
[Glow Be Gone SKSE Updated](https://www.nexusmods.com/skyrimspecialedition/mods/34148) - I'm not about that glowing life.
[Glow be Gone SKSE Updated GhostFX Workaround](https://www.nexusmods.com/skyrimspecialedition/mods/36112) - Sadly not being about that glowing life can break ghosts a bit.
[Ghost Shader](https://www.nexusmods.com/enderalspecialedition/mods/105) - Alternatively, nicer looking ghosts. 
[Smart No More Stupid Dog Comments](https://www.nexusmods.com/skyrimspecialedition/mods/5226) - No dogs are stupid.
[no dogs are stupid](https://www.nexusmods.com/skyrimspecialedition/mods/60084) - No, like, **no** dogs are stupid.

Enderal Specific:
[Enderal Distinctive Jewelry](https://www.nexusmods.com/enderalspecialedition/mods/370) - I really like the look of this jewelry, that's really it.
[Akropolis Stones 8K HD Retexture](https://www.nexusmods.com/enderalspecialedition/mods/393) - Genuinely makes it easier to click the right perk when the stones are really clear.
[EAWO - Keeper armour, and NPC](https://www.nexusmods.com/enderalspecialedition/mods/208?tab=files) - I really like the changes to what NPCs wear, added by these two.
[Unique Enderal Uniques SE](https://www.nexusmods.com/enderalspecialedition/mods/38) - Unique stuff is neat. I like Unique stuff.
[Even More Unique Weapons (now with a brand new staff)](https://www.nexusmods.com/enderalspecialedition/mods/95) - More unique stuff! 
[Enderal SE - Conditional Expressions](https://www.nexusmods.com/enderalspecialedition/mods/314) 
[Enderal SE - Immersive Interactions](https://www.nexusmods.com/enderalspecialedition/mods/317) - I like these animation additions
[Less silly potions Enderal SE](https://www.nexusmods.com/enderalspecialedition/mods/85) - This goes really well with the rest of the vibe of this list, making potions much more understated.
[Quieter Sun Temple Water](https://www.nexusmods.com/enderalspecialedition/mods/309) - It's just _so loud_.
[Silent Summon Apparition](https://www.nexusmods.com/enderalspecialedition/mods/288) - It's just **_so loud_**.
[Sounds for Collectibles](https://www.nexusmods.com/enderalspecialedition/mods/349) - Just makes them much easier to find.
[Circlets hoods and hats](https://www.nexusmods.com/enderalspecialedition/mods/258) - Classic
[tailsmans and amulets together](https://www.nexusmods.com/enderalspecialedition/mods/344) - Let me have my ghost friend

These three fit together in order to make the bookcases in the player homes useable:
[Close All Books](https://www.nexusmods.com/enderalspecialedition/mods/324)
[bookshelves script SKSE](https://www.nexusmods.com/skyrim/mods/24359)
[Dynamic Bookcases](https://www.nexusmods.com/enderalspecialedition/mods/325)

Some more game breaky stuff:
[Stronger Summons](https://www.nexusmods.com/enderalspecialedition/mods/202) - Makes summons level with the player, so that wolf doesn't stay lvl 5, as in base game, but scales with you for a bit, up to level 50.
[Leveling Redone (No Skillbooks)](https://www.nexusmods.com/enderalspecialedition/mods/267) - This could be an optional mod, but it removes the skillbooks from the game, and adds an area in the meditation area, for you to level your skills.

**Comment by Guitarninja2** [comment]
Grabbed the ones I liked. Thank you!
