### ISSUE TITLE
Armor Disappearing on Character 

### ISSUE THREAD

**Issue by Blank5SZ** [Guitarninja2/thepath#7]
My characters race is half Qyranian  and for some reason certain armors are invisible so far I've seen the Roughspun tunic as invisible the leather cape as invisible the roughspun fur armor as invisible those are the only ones I've noticed up to now
![20220427182923_1](https://user-images.githubusercontent.com/104533116/165635014-3d230811-67d7-4c46-9f4d-4ec58e229c97.jpg)
![20220427182917_1](https://user-images.githubusercontent.com/104533116/165635021-3f9063ed-5d38-4e4c-8694-348e993121e5.jpg)
![20220427182912_1](https://user-images.githubusercontent.com/104533116/165635029-ef54a20d-29e4-4452-98b6-7e853291a775.jpg)

Here in the Screenshots, you will see I have the Piece of Armor Equipped in my Inventory but it does not show up on my Character

**Comment by Guitarninja2** [comment]
Fixed in 1.0.1
