### ISSUE TITLE
Mismatched textures

### ISSUE THREAD

**Issue by Culetto** [Guitarninja2/thepath#9]
![enb2022_5_3_18_13_00](https://user-images.githubusercontent.com/88935956/166493797-40437dc9-a2a3-42a9-83ad-62505cfbd2d7.png)
![enb2022_5_3_18_13_12](https://user-images.githubusercontent.com/88935956/166493963-99e9378a-fc69-44e7-9f11-a756c8d4ce57.png)
![enb2022_5_3_17_51_13](https://user-images.githubusercontent.com/88935956/166494032-818579ca-3b92-424e-b3f9-800188273a20.png)
found mismatched textures near old custom facilities in the ark area

**Comment by geophyzz** [comment]
Here is ground straw near the Prison in Ark
![20220502193624_1](https://user-images.githubusercontent.com/55920444/166563623-13274fa4-1869-49c1-8a24-3a8340c1e94d.jpg)

**Comment by Blank5SZ** [comment]
Weird ive never had this issue did you mess with the load order?

**Comment by geophyzz** [comment]
Not me.  Running stock Path 1.0.1, but saw it on 1.0 too. I have Performance Grass on, but don't think that could cause it.

**Comment by Culetto** [comment]
> Weird ive never had this issue did you mess with the load order?

I only installed 2 mods that are not part of the modlist, Sounds for collectibles and massless psionics apart from that i haven't touched the load order at all. I'm not playing in performance mode either

**Comment by Guitarninja2** [comment]
Apparently it was an ENB issue. Fixed now.
